/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class swisseph_SwephExp */

#ifndef _Included_swisseph_SwephExp
#define _Included_swisseph_SwephExp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     swisseph_SwephExp
 * Method:    heliacal_ut
 * Signature: (D[D[D[DLjava/lang/String;II[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_heliacal_1ut
  (JNIEnv *, jclass thiz, jdouble, jdoubleArray, jdoubleArray, jdoubleArray, jstring, jint, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    heliacal_pheno_ut
 * Signature: (D[D[D[DLjava/lang/StringBuilder;II[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_heliacal_1pheno_1ut
  (JNIEnv *, jclass thiz, jdouble, jdoubleArray, jdoubleArray, jdoubleArray, jstring, jint, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    vis_limit_mag
 * Signature: (D[D[D[DLjava/lang/StringBuilder;I[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_vis_1limit_1mag
  (JNIEnv *, jclass thiz, jdouble, jdoubleArray, jdoubleArray, jdoubleArray, jobject, jint, jdoubleArray, jobject);

JNIEXPORT jdouble JNICALL
Java_com_example_swelib_SwephExp_solcross_1ut(JNIEnv *env, jobject swephexp,
                                                               jdouble x2cross, jdouble jd_ut, jint flag, jobject errBuilder) ;
/*
 * Class:     swisseph_SwephExp
 * Method:    heliacal_angle
 * Signature: (D[D[D[DIDDDDD[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_heliacal_1angle
  (JNIEnv *, jclass thiz, jdouble, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    topo_arcus_visionis
 * Signature: (D[D[D[DIDDDDDD[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_topo_1arcus_1visionis
  (JNIEnv *, jclass thiz, jdouble, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    set_astro_models
 * Signature: (Ljava/lang/StringBuilder;I)V
 */
JNIEXPORT void JNICALL Java_com_example_swelib_SwephExp_set_1astro_1models
  (JNIEnv *, jclass thiz, jobject, jint);

/*
 * Class:     swisseph_SwephExp
 * Method:    get_astro_models
 * Signature: (Ljava/lang/StringBuilder;Ljava/lang/StringBuilder;I)V
 */
JNIEXPORT void JNICALL Java_com_example_swelib_SwephExp_get_1astro_1models
  (JNIEnv *, jclass thiz, jobject, jobject, jint);

/*
 * Class:     swisseph_SwephExp
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_swelib_SwephExp_version
  (JNIEnv *, jclass thiz);

/*
 * Class:     swisseph_SwephExp
 * Method:    get_library_path
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_swelib_SwephExp_get_1library_1path
  (JNIEnv *, jclass thiz);

/*
 * Class:     swisseph_SwephExp
 * Method:    calc
 * Signature: (DII[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_calc
  (JNIEnv *, jclass thiz, jdouble, jint, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    calc_ut
 * Signature: (DII[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_calc_1ut
  (JNIEnv *, jclass thiz, jdouble, jint, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    calc_pctr
 * Signature: (DIII[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_calc_1pctr
  (JNIEnv *, jclass thiz, jdouble, jint, jint, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    fixstar
 * Signature: (Ljava/lang/StringBuilder;DI[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_fixstar
  (JNIEnv *, jclass thiz, jobject, jdouble, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    fixstar_ut
 * Signature: (Ljava/lang/StringBuilder;DI[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_fixstar_1ut
  (JNIEnv *, jclass thiz, jobject, jdouble, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    fixstar_mag
 * Signature: (Ljava/lang/StringBuilder;[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_fixstar_1mag
  (JNIEnv *, jclass thiz, jobject, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    fixstar2
 * Signature: (Ljava/lang/StringBuilder;DI[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_fixstar2
  (JNIEnv *, jclass thiz, jobject, jdouble, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    fixstar2_ut
 * Signature: (Ljava/lang/StringBuilder;DI[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_fixstar2_1ut
  (JNIEnv *, jclass thiz, jobject, jdouble, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    fixstar2_mag
 * Signature: (Ljava/lang/StringBuilder;[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_fixstar2_1mag
  (JNIEnv *, jclass thiz, jobject, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_swelib_SwephExp_close
  (JNIEnv *, jclass thiz);

/*
 * Class:     swisseph_SwephExp
 * Method:    set_ephe_path
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_swelib_SwephExp_set_1ephe_1path
  (JNIEnv *, jclass thiz, jstring);

/*
 * Class:     swisseph_SwephExp
 * Method:    set_jpl_file
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_swelib_SwephExp_set_1jpl_1file
  (JNIEnv *, jclass thiz, jstring);

/*
 * Class:     swisseph_SwephExp
 * Method:    get_planet_name
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_swelib_SwephExp_get_1planet_1name
  (JNIEnv *, jclass thiz, jint);

/*
 * Class:     swisseph_SwephExp
 * Method:    set_topo
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_com_example_swelib_SwephExp_set_1topo
  (JNIEnv *, jclass thiz, jdouble, jdouble, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    set_sid_mode
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_com_example_swelib_SwephExp_set_1sid_1mode
  (JNIEnv *, jclass thiz, jint, jdouble, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    get_ayanamsa_ex
 * Signature: (DI[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_get_1ayanamsa_1ex
  (JNIEnv *, jclass thiz, jdouble, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    get_ayanamsa_ex_ut
 * Signature: (DI[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_get_1ayanamsa_1ex_1ut
  (JNIEnv *, jclass thiz, jdouble, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    get_ayanamsa
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_swelib_SwephExp_get_1ayanamsa
  (JNIEnv *, jclass thiz, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    get_ayanamsa_ut
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_swelib_SwephExp_get_1ayanamsa_1ut
  (JNIEnv *, jclass thiz, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    get_ayanamsa_name
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_swelib_SwephExp_get_1ayanamsa_1name
  (JNIEnv *, jclass thiz, jint);

/*
 * Class:     swisseph_SwephExp
 * Method:    get_current_file_data
 * Signature: (I[D[D[I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_swelib_SwephExp_get_1current_1file_1data
  (JNIEnv *, jclass thiz, jint, jdoubleArray, jdoubleArray, jintArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    date_conversion
 * Signature: (IIIDC[D)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_date_1conversion
  (JNIEnv *, jclass thiz, jint, jint, jint, jdouble, jchar, jdoubleArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    julday
 * Signature: (IIIDI)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_swelib_SwephExp_julday
  (JNIEnv *, jclass thiz, jint, jint, jint, jdouble, jint);


/*
 * Class:     swisseph_SwephExp
 * Method:    revjul
 * Signature: (DI[I[D)V
 */
JNIEXPORT void JNICALL Java_com_example_swelib_SwephExp_revjul
  (JNIEnv *, jclass thiz, jdouble, jint, jintArray, jdoubleArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    utc_to_jd
 * Signature: (IIIIIDI[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_utc_1to_1jd
  (JNIEnv *, jclass thiz, jint, jint, jint, jint, jint, jdouble, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    jdet_to_utc
 * Signature: (DI[I[D)V
 */
JNIEXPORT void JNICALL Java_com_example_swelib_SwephExp_jdet_1to_1utc
  (JNIEnv *, jclass thiz, jdouble, jint, jintArray, jdoubleArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    jdut1_to_utc
 * Signature: (DI[I[D)V
 */
JNIEXPORT void JNICALL Java_com_example_swelib_SwephExp_jdut1_1to_1utc
  (JNIEnv *, jclass thiz, jdouble, jint, jintArray, jdoubleArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    utc_time_zone
 * Signature: (IIIIIDD[I[D)V
 */
JNIEXPORT void JNICALL Java_com_example_swelib_SwephExp_utc_1time_1zone
  (JNIEnv *, jclass thiz, jint, jint, jint, jint, jint, jdouble, jdouble, jintArray, jdoubleArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    houses
 * Signature: (DDDI[D[D)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_houses
  (JNIEnv *, jclass thiz, jdouble, jdouble, jdouble, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    houses_ex
 * Signature: (DIDDI[D[D)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_houses_1ex
  (JNIEnv *, jclass thiz, jdouble, jint, jdouble, jdouble, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    houses_ex2
 * Signature: (DIDDI[D[D[D[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_houses_1ex2
  (JNIEnv *, jclass thiz, jdouble, jint, jdouble, jdouble, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    houses_armc
 * Signature: (DDDI[D[D)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_houses_1armc
  (JNIEnv *, jclass thiz, jdouble, jdouble, jdouble, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    houses_armc_ex2
 * Signature: (DDDI[D[D[D[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_houses_1armc_1ex2
  (JNIEnv *, jclass thiz, jdouble, jdouble, jdouble, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    house_pos
 * Signature: (DDDI[DLjava/lang/StringBuilder;)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_swelib_SwephExp_house_1pos
  (JNIEnv *, jclass thiz, jdouble, jdouble, jdouble, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    house_name
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_swelib_SwephExp_house_1name
  (JNIEnv *, jclass thiz, jint);

/*
 * Class:     swisseph_SwephExp
 * Method:    gauquelin_sector
 * Signature: (DILjava/lang/StringBuilder;II[DDD[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_gauquelin_1sector
  (JNIEnv *, jclass thiz, jdouble, jint, jobject, jint, jint, jdoubleArray, jdouble, jdouble, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    sol_eclipse_where
 * Signature: (DI[D[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_sol_1eclipse_1where
  (JNIEnv *, jclass thiz, jdouble, jint, jdoubleArray, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    lun_occult_where
 * Signature: (DILjava/lang/StringBuilder;I[D[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_lun_1occult_1where
  (JNIEnv *, jclass thiz, jdouble, jint, jobject, jint, jdoubleArray, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    sol_eclipse_how
 * Signature: (DI[D[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_sol_1eclipse_1how
  (JNIEnv *, jclass thiz, jdouble, jint, jdoubleArray, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    sol_eclipse_when_loc
 * Signature: (DI[D[D[DILjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_sol_1eclipse_1when_1loc
  (JNIEnv *, jclass thiz, jdouble, jint, jdoubleArray, jdoubleArray, jdoubleArray, jint, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    lun_occult_when_loc
 * Signature: (DILjava/lang/StringBuilder;I[D[D[DILjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_lun_1occult_1when_1loc
  (JNIEnv *, jclass thiz, jdouble, jint, jobject, jint, jdoubleArray, jdoubleArray, jdoubleArray, jint, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    sol_eclipse_when_glob
 * Signature: (DII[DILjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_sol_1eclipse_1when_1glob
  (JNIEnv *, jclass thiz, jdouble, jint, jint, jdoubleArray, jint, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    lun_occult_when_glob
 * Signature: (DILjava/lang/StringBuilder;II[DILjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_lun_1occult_1when_1glob
  (JNIEnv *, jclass thiz, jdouble, jint, jobject, jint, jint, jdoubleArray, jint, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    lun_eclipse_how
 * Signature: (DI[D[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_lun_1eclipse_1how
  (JNIEnv *, jclass thiz, jdouble, jint, jdoubleArray, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    lun_eclipse_when
 * Signature: (DII[DILjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_lun_1eclipse_1when
  (JNIEnv *, jclass thiz, jdouble, jint, jint, jdoubleArray, jint, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    lun_eclipse_when_loc
 * Signature: (DI[D[D[DILjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_lun_1eclipse_1when_1loc
  (JNIEnv *, jclass thiz, jdouble, jint, jdoubleArray, jdoubleArray, jdoubleArray, jint, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    pheno
 * Signature: (DII[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_pheno
  (JNIEnv *, jclass thiz, jdouble, jint, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    pheno_ut
 * Signature: (DII[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_pheno_1ut
  (JNIEnv *, jclass thiz, jdouble, jint, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    refrac
 * Signature: (DDDI)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_swelib_SwephExp_refrac
  (JNIEnv *, jclass thiz, jdouble, jdouble, jdouble, jint);

/*
 * Class:     swisseph_SwephExp
 * Method:    refrac_extended
 * Signature: (DDDDDI[D)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_swelib_SwephExp_refrac_1extended
  (JNIEnv *, jclass thiz, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jdoubleArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    set_lapse_rate
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_example_swelib_SwephExp_set_1lapse_1rate
  (JNIEnv *, jclass thiz, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    azalt
 * Signature: (DI[DDD[D[D)V
 */
JNIEXPORT void JNICALL Java_com_example_swelib_SwephExp_azalt
  (JNIEnv *, jclass thiz, jdouble, jint, jdoubleArray, jdouble, jdouble, jdoubleArray, jdoubleArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    azalt_rev
 * Signature: (DI[D[D[D)V
 */
JNIEXPORT void JNICALL Java_com_example_swelib_SwephExp_azalt_1rev
  (JNIEnv *, jclass thiz, jdouble, jint, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    rise_trans_true_hor
 * Signature: (DILjava/lang/StringBuilder;II[DDDD[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_rise_1trans_1true_1hor
  (JNIEnv *, jclass thiz, jdouble, jint, jobject, jint, jint, jdoubleArray, jdouble, jdouble, jdouble, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    rise_trans
 * Signature: (DILjava/lang/StringBuilder;II[DDD[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_rise_1trans
  (JNIEnv *, jclass thiz, jdouble, jint, jobject, jint, jint, jdoubleArray, jdouble, jdouble, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    nod_aps
 * Signature: (DIII[D[D[D[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_nod_1aps
  (JNIEnv *, jclass thiz, jdouble, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    nod_aps_ut
 * Signature: (DIII[D[D[D[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_nod_1aps_1ut
  (JNIEnv *, jclass thiz, jdouble, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    get_orbital_elements
 * Signature: (DII[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_get_1orbital_1elements
  (JNIEnv *, jclass thiz, jdouble, jint, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    orbit_max_min_true_distance
 * Signature: (DII[D[D[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_orbit_1max_1min_1true_1distance
  (JNIEnv *, jclass thiz, jdouble, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    deltat
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_swelib_SwephExp_deltat
  (JNIEnv *, jclass thiz, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    deltat_ex
 * Signature: (DILjava/lang/StringBuilder;)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_swelib_SwephExp_deltat_1ex
  (JNIEnv *, jclass thiz, jdouble, jint, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    time_equ
 * Signature: (D[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_time_1equ
  (JNIEnv *, jclass thiz, jdouble, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    lmt_to_lat
 * Signature: (DD[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_lmt_1to_1lat
  (JNIEnv *, jclass thiz, jdouble, jdouble, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    lat_to_lmt
 * Signature: (DD[DLjava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwephExp_lat_1to_1lmt
  (JNIEnv *, jclass thiz, jdouble, jdouble, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    sidtime0
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_swelib_SwephExp_sidtime0
  (JNIEnv *, jclass thiz, jdouble, jdouble, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    sidtime
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_swelib_SwephExp_sidtime
  (JNIEnv *, jclass thiz, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    set_interpolate_nut
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_swelib_SwephExp_set_1interpolate_1nut
  (JNIEnv *, jclass thiz, jint);

/*
 * Class:     swisseph_SwephExp
 * Method:    cotrans
 * Signature: ([D[DD)V
 */
JNIEXPORT void JNICALL Java_com_example_swelib_SwephExp_cotrans
  (JNIEnv *, jclass thiz, jdoubleArray, jdoubleArray, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    cotrans_sp
 * Signature: ([D[DD)V
 */
JNIEXPORT void JNICALL Java_com_example_swelib_SwephExp_cotrans_1sp
  (JNIEnv *, jclass thiz, jdoubleArray, jdoubleArray, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    get_tid_acc
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_example_swelib_SwephExp_get_1tid_1acc
  (JNIEnv *, jclass thiz);

/*
 * Class:     swisseph_SwephExp
 * Method:    set_tid_acc
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_example_swelib_SwephExp_set_1tid_1acc
  (JNIEnv *, jclass thiz, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    set_delta_t_userdef
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_example_swelib_SwephExp_set_1delta_1t_1userdef
  (JNIEnv *, jclass thiz, jdouble);


/*
 * Class:     swisseph_SwephExp
 * Method:    degnorm
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_swelib_SwephExp_degnorm
  (JNIEnv *, jclass thiz, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    radnorm
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_swelib_SwephExp_radnorm
  (JNIEnv *, jclass thiz, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    rad_midp
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_swelib_SwephExp_rad_1midp
  (JNIEnv *, jclass thiz, jdouble, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    deg_midp
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_swelib_SwephExp_deg_1midp
  (JNIEnv *, jclass thiz, jdouble, jdouble);

/*
 * Class:     swisseph_SwephExp
 * Method:    split_deg
 * Signature: (DI[I[D[I)V
 */
JNIEXPORT void JNICALL Java_com_example_swelib_SwephExp_split_1deg
  (JNIEnv *, jclass thiz, jdouble, jint, jintArray, jdoubleArray, jintArray);

JNIEXPORT jint JNICALL
Java_com_example_swelib_SwissEph_convertBaziToDates(JNIEnv * , jobject thiz, jint,
                                                    jint, jint, jint, jdouble,
                                                    jint, jint,
                                                    jdoubleArray);

/*
 * Class:     swisseph_SwephExp
 * Method:    solcross
 */
JNIEXPORT jdouble JNICALL Java_com_example_swelib_SwissEph_solcross
        (JNIEnv *, jobject thiz, jdouble, jdouble, jint, jobject);


/*
 * Class:     swisseph_SwephExp
 * Method:    mooncross
 */
JNIEXPORT jdouble JNICALL Java_com_example_swelib_SwissEph_mooncross
        (JNIEnv *, jobject thiz, jdouble, jdouble, jint, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    mooncross_ut
 */
JNIEXPORT jdouble JNICALL Java_com_example_swelib_SwissEph_mooncross_1ut
        (JNIEnv *, jobject thiz, jdouble, jdouble, jint, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    mooncross_node
 */
JNIEXPORT jdouble JNICALL Java_com_example_swelib_SwissEph_mooncross_1node
        (JNIEnv *, jobject thiz, jdouble, jint, jdoubleArray, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    mooncross_node_ut
 */
JNIEXPORT jdouble JNICALL Java_com_example_swelib_SwissEph_mooncross_1node_1ut
        (JNIEnv *, jobject thiz, jdouble, jint, jdoubleArray, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    helio_cross
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwissEph_helio_1cross
        (JNIEnv *, jobject thiz, jint, jdouble, jdouble, jint, jint, jdoubleArray, jobject);

/*
 * Class:     swisseph_SwephExp
 * Method:    helio_cross_ut
 */
JNIEXPORT jint JNICALL Java_com_example_swelib_SwissEph_helio_1cross_1ut
        (JNIEnv *, jobject thiz, jint, jdouble, jdouble, jint, jint, jdoubleArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
